--
-- Test schema for RDF engine
--

SCHEMA SMOKE_TEST;

--- Diamond inheritance and repeated attributes

ENTITY DiamondBase
	AttrBase : STRING;
END_ENTITY;

ENTITY DiamondLeft SUBTYPE OF (DiamondBase);
	AttrCommonName : STRING;
END_ENTITY;

ENTITY DiamondRight2 SUBTYPE OF (DiamondBase);
	AttrRight : STRING;
END_ENTITY;

ENTITY DiamondRight SUBTYPE OF (DiamondRight2);
	NotFirst	   : STRING;
	AttrCommonName : STRING;
END_ENTITY;

ENTITY Diamond SUBTYPE OF (DiamondLeft, DiamondRight);
	AttrChild : STRING;
END_ENTITY;

--- ANDOR subtypes

ENTITY Person
	Name : STRING;
END_ENTITY;

ENTITY Child SUBTYPE OF (Person)
	ParentName : STRING;
END_ENTITY;

ENTITY Parent SUBTYPE OF (Person)
	ChildName : STRING;
END_ENTITY;
