--
-- Test schema for RDF engine
--

SCHEMA SMOKE_TEST;

--- Diamond inheritance and repeated attributes

ENTITY DiamondBase
	AttrBase : STRING;
END_ENTITY;

ENTITY DiamondLeft SUBTYPE OF (DiamondBase);
	AttrCommonName : STRING;
INVERSE
	Inv		  : SET OF Child FOR LDiamond;
DERIVE
	Drv : STRING := 'Derived_DiamondLeft';
END_ENTITY;

ENTITY DiamondRight2 SUBTYPE OF (DiamondBase);
	AttrRight : STRING;
INVERSE
	Inv		  : SET OF Parent FOR RDiamond;
END_ENTITY;

ENTITY DiamondRight SUBTYPE OF (DiamondRight2);
	Owner		   : Person;
	AttrCommonName : STRING;
DERIVE
	Drv : STRING := 'Derived_DiamondRight';
END_ENTITY;

ENTITY Diamond SUBTYPE OF (DiamondLeft, DiamondRight);
	AttrChild : STRING;
END_ENTITY;

--- ANDOR subtypes

ENTITY PersonBase
	Skip : NUMBER;
END_ENTITY;

ENTITY Person SUBTYPE OF (PersonBase)
	Name : STRING;
INVERSE
	HasDiamonds : SET OF DiamondRight FOR Owner;
END_ENTITY;

ENTITY Child SUBTYPE OF (Person)
	ParentName	: STRING;
	LDiamond	: DiamondLeft;
END_ENTITY;

ENTITY Parent SUBTYPE OF (Person)
	ChildName : STRING;
	RDiamond  : DiamondRight2;
END_ENTITY;
