//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkOnlyKernel {
            get {
                return ((bool)(this["chkOnlyKernel"]));
            }
            set {
                this["chkOnlyKernel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbIncludePath_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbIncludePath_history"]));
            }
            set {
                this["cbIncludePath_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbLibFile_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbLibFile_history"]));
            }
            set {
                this["cbLibFile_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbDllFile_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbDllFile_history"]));
            }
            set {
                this["cbDllFile_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbEngineCs_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbEngineCs_history"]));
            }
            set {
                this["cbEngineCs_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbIfcEngineCs_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbIfcEngineCs_history"]));
            }
            set {
                this["cbIfcEngineCs_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbEbApi_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbEbApi_history"]));
            }
            set {
                this["cbEbApi_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbIncludePath_value {
            get {
                return ((string)(this["KernelTest_cbIncludePath_value"]));
            }
            set {
                this["KernelTest_cbIncludePath_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbIncludePath_value {
            get {
                return ((string)(this["IFCTest_cbIncludePath_value"]));
            }
            set {
                this["IFCTest_cbIncludePath_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbLibFile_value {
            get {
                return ((string)(this["KernelTest_cbLibFile_value"]));
            }
            set {
                this["KernelTest_cbLibFile_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbLibFile_value {
            get {
                return ((string)(this["IFCTest_cbLibFile_value"]));
            }
            set {
                this["IFCTest_cbLibFile_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbDllFile_value {
            get {
                return ((string)(this["KernelTest_cbDllFile_value"]));
            }
            set {
                this["KernelTest_cbDllFile_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbDllFile_value {
            get {
                return ((string)(this["IFCTest_cbDllFile_value"]));
            }
            set {
                this["IFCTest_cbDllFile_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbEngineCs_value {
            get {
                return ((string)(this["KernelTest_cbEngineCs_value"]));
            }
            set {
                this["KernelTest_cbEngineCs_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbEngineCs_value {
            get {
                return ((string)(this["IFCTest_cbEngineCs_value"]));
            }
            set {
                this["IFCTest_cbEngineCs_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbIfcEngineCs_value {
            get {
                return ((string)(this["IFCTest_cbIfcEngineCs_value"]));
            }
            set {
                this["IFCTest_cbIfcEngineCs_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbIfcEngineCs_value {
            get {
                return ((string)(this["KernelTest_cbIfcEngineCs_value"]));
            }
            set {
                this["KernelTest_cbIfcEngineCs_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbEbApi_value {
            get {
                return ((string)(this["KernelTest_cbEbApi_value"]));
            }
            set {
                this["KernelTest_cbEbApi_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbEbApi_value {
            get {
                return ((string)(this["IFCTest_cbEbApi_value"]));
            }
            set {
                this["IFCTest_cbEbApi_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cbGeomCs_history {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cbGeomCs_history"]));
            }
            set {
                this["cbGeomCs_history"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KernelTest_cbGeomCs_value {
            get {
                return ((string)(this["KernelTest_cbGeomCs_value"]));
            }
            set {
                this["KernelTest_cbGeomCs_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IFCTest_cbGeomCs_value {
            get {
                return ((string)(this["IFCTest_cbGeomCs_value"]));
            }
            set {
                this["IFCTest_cbGeomCs_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkToolBoxEx {
            get {
                return ((bool)(this["chkToolBoxEx"]));
            }
            set {
                this["chkToolBoxEx"] = value;
            }
        }
    }
}
